from dotenv import load_dotenv
import analysis
import telegram_post
import fetch

load_dotenv()

if __name__ == "__main__":
    # fetch an article link from RSS feed
    article_url = fetch.fetch_article_link()
    # fetch the actual article text from the link
    event = fetch.fetch_article_text(article_url)
    # analyze the event and post the formatted text to Telegram
    # raw object means that the analyze_event does not return a formatted string, it returns an EventAnalysis object that contains the analysis results.
    raw_object = analysis.analyze_event(event)
    # fetch an image from Pexels based on the image query generated by the LLM and post it to Telegram
    image_query = raw_object.image_query
    photo_url = fetch.fetch_image_from_pexels(image_query)
    telegram_post.post_image(photo_url, raw_object.headline)
    # post the remaining text to Telegram as a separate message
    formatted_text = raw_object.to_text()
    telegram_post.post_text(formatted_text)
